<h1>Queries: <?= count($queries) ?>, time: <?= $totalTime ?> ms, <?= $connectionName ?></h1>
<div class="tracy-inner tracy-Eloquent">
  <table>
    <tr>
      <th>SQL</th>
      <th>Bindings</th>
      <th>Time (ms)</th>
    </tr>
    <?php foreach($queries as $query): ?>
      <tr>
        <td><?= $query->sql ?></td>
        <td><pre><?= implode(', ', $query->bindings) ?></pre></td>
        <td><?= $query->time ?></td>
      </tr>
    <?php endforeach; ?>
  </table>
</div>
